name: CI

on: [push]

jobs:
  abaplint:
    runs-on: ubuntu-latest
    steps:
    - name: abaplint
      uses: tobiaszgithub/actions-abaplint@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
